# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Check the incoming inputs.'
description: |
  This action is designed to be used to check the incoming
  inputs (dynamically generated).

runs:
  using: "composite"
  steps:
    - name: Check inputs
      shell: bash
      run: |
        # Check inputs
        echo "All inputs:"
        echo "----------------"
        echo '${{ toJSON(inputs) }}' | jq
