# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup KinD'
description: |
  This action sets up a KinD cluster based on the supplied
  configuration knobs.

inputs:
  k8s-version:
    description: |
      The version of Kubernetes to use in the form: 1.24.x
    required: true
    default: 1.24.x

  kind-version:
    description: |
      The exact version of KinD to use in the form: 0.20.0
    required: true
    default: 0.20.0

  kind-worker-count:
    description: |
      The number of worker nodes in the cluster
    required: true
    default: "1"

  registry-authority:
    description: |
      The authority of the registry in the form {hostname}:{port}
    required: true
    default: registry.local:5000

  registry-mirror:
    description: |
      The hostname of a registry mirror to configure KinD to use (to avoid DockerHub rate limits).
    required: true # TODO(mattmoor): Make this optional
    default: mirror.gcr.io

  registry-username:
    description: |
      Username for setting up a private registry (optional).
    required: false
    default: ""

  registry-password:
    description: |
      Password for setting up a private registry (optional).
    required: false
    default: ""

  cluster-suffix:
    description: |
      The suffix to use for Kubernetes services on this cluster.
    required: true
    default: cluster.local

  registry-volume:
    description: |
      A directory path to be used for the registry volume
    required: false
    default: ""

outputs:
  kind-start-time:
    description: |
      The timestamp when the Kind cluster started.
    value: ${{ steps.start-time.outputs.kind-start-time }}

runs:
  using: "composite"

  steps:
    - name: Install KinD
      shell: bash
      run: |
        # Disable swap otherwise memory enforcement does not work
        # See: https://kubernetes.slack.com/archives/CEKK1KTN2/p1600009955324200
        sudo swapoff -a
        sudo rm -f /swapfile

        # Use in-memory storage to avoid etcd server timeouts.
        # https://kubernetes.slack.com/archives/CEKK1KTN2/p1615134111016300
        # https://github.com/kubernetes-sigs/kind/issues/845
        sudo mkdir -p /tmp/etcd
        sudo mount -t tmpfs tmpfs /tmp/etcd

        curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v${{ inputs.kind-version }}/kind-$(uname)-amd64"
        chmod +x ./kind
        sudo mv kind /usr/local/bin

    - name: Determine KinD Image
      shell: bash
      run: |
        K8SVERSION=${{ inputs.k8s-version }}
        case ${K8SVERSION//v} in

          1.21.x)
            echo "KIND_IMAGE=kindest/node:v1.21.14@sha256:8a4e9bb3f415d2bb81629ce33ef9c76ba514c14d707f9797a01e3216376ba093" >> $GITHUB_ENV
            ;;

          1.22.x)
            echo "KIND_IMAGE=kindest/node:v1.22.17@sha256:f5b2e5698c6c9d6d0adc419c0deae21a425c07d81bbf3b6a6834042f25d4fba2" >> $GITHUB_ENV
            ;;

          1.23.x)
            echo "KIND_IMAGE=kindest/node:v1.23.17@sha256:59c989ff8a517a93127d4a536e7014d28e235fb3529d9fba91b3951d461edfdb" >> $GITHUB_ENV
            ;;

          1.24.x)
            echo "KIND_IMAGE=kindest/node:v1.24.15@sha256:7db4f8bea3e14b82d12e044e25e34bd53754b7f2b0e9d56df21774e6f66a70ab" >> $GITHUB_ENV
            ;;

          1.25.x)
            echo "KIND_IMAGE=kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8" >> $GITHUB_ENV
            ;;

          1.26.x)
            echo "KIND_IMAGE=kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb" >> $GITHUB_ENV
            ;;

          1.27.x)
            echo "KIND_IMAGE=kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72" >> $GITHUB_ENV
            ;;

          *) echo "Unsupported version: ${{ inputs.k8s-version }}"; exit 1 ;;
        esac

    - name: Determine Registry Host and Port
      shell: bash
      run: |
        echo "REGISTRY_NAME=$(echo ${{ inputs.registry-authority }} | cut -d':' -f 1)" >> $GITHUB_ENV
        echo "REGISTRY_PORT=$(echo ${{ inputs.registry-authority }} | cut -d':' -f 2)" >> $GITHUB_ENV

    - name: Create KinD Cluster
      shell: bash
      run: |
        cat > kind.yaml <<EOF
        apiVersion: kind.x-k8s.io/v1alpha4
        kind: Cluster
        nodes:
        - role: control-plane
          image: "${KIND_IMAGE}"
          extraMounts:
          - containerPath: /var/lib/etcd
            hostPath: /tmp/etcd
        EOF

        for node in {1..${{ inputs.kind-worker-count }}}; do
        cat >> kind.yaml <<EOF
        - role: worker
          image: "${KIND_IMAGE}"
        EOF
        done

        cat >> kind.yaml <<EOF
        # Configure registry for KinD.
        containerdConfigPatches:
        - |-
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors."$REGISTRY_NAME:$REGISTRY_PORT"]
            endpoint = ["http://$REGISTRY_NAME:$REGISTRY_PORT"]
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
            endpoint = ["https://${{ inputs.registry-mirror }}"]

        # This is needed in order to support projected volumes with service account tokens.
        # See: https://kubernetes.slack.com/archives/CEKK1KTN2/p1600268272383600
        kubeadmConfigPatches:
          - |
            kind: ClusterConfiguration
            metadata:
              name: config
            apiServer:
              extraArgs:
                "service-account-issuer": "https://kubernetes.default.svc"
                "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
                "service-account-jwks-uri": "https://kubernetes.default.svc/openid/v1/jwks"
                "service-account-key-file": "/etc/kubernetes/pki/sa.pub"
        EOF

        if [[ "${{ inputs.cluster-suffix }}" != "cluster.local" ]]; then
        cat >> kind.yaml <<EOF
            networking:
              dnsDomain: "${{ inputs.cluster-suffix }}"
        EOF
        fi

        echo '::group:: KinD config'
        cat kind.yaml
        echo '::endgroup::'

        kind create cluster --config kind.yaml --wait 5m

    - name: Expose OIDC Discovery
      shell: bash
      run: |
        # From: https://banzaicloud.com/blog/kubernetes-oidc/
        # To be able to fetch the public keys and validate the JWT tokens against
        # the Kubernetes cluster's issuer we have to allow external unauthenticated
        # requests. To do this, we bind this special role with a ClusterRoleBinding
        # to unauthenticated users (make sure that this is safe in your environment,
        # but only public keys are visible on this URL)
        kubectl create clusterrolebinding oidc-reviewer \
          --clusterrole=system:service-account-issuer-discovery \
          --group=system:unauthenticated

    - name: Install metallb
      shell: bash
      run: |
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.5/config/manifests/metallb-native.yaml
        kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

        # Wait for metallb to be ready (or webhook will reject CRDs)
        for x in $(kubectl get deploy --namespace metallb-system -oname); do
          kubectl rollout status --timeout 5m --namespace metallb-system "$x"
        done

        network=$(docker network inspect kind -f "{{(index .IPAM.Config 0).Subnet}}" | cut -d '.' -f1,2)
        cat <<EOF >> ./metallb-crds.yaml
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: config
          namespace: metallb-system
        spec:
          addresses:
          - $network.255.1-$network.255.250
        ---
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: empty
          namespace: metallb-system
        EOF

        for i in {1..10}
        do
          if kubectl apply -f ./metallb-crds.yaml ; then
            echo successfully applied metallb crds
            break
          fi
          if [ $i == 10 ]; then
            echo failed to apply metallb crds. exiting
            exit 1
          fi

          echo failed to apply metallb crds. Attempt numer $i, retrying
          sleep 2
        done

    - name: Setup Container Registry
      shell: bash
      run: |
        # If username/password provided, create an htpasswd file which
        # will be mounted into the registry container
        EXTRA_ARGS=()
        USERNAME="${{ inputs.registry-username }}"
        PASSWORD="${{ inputs.registry-password }}"
        if [[ "${USERNAME}" != "" ]] && [[ "${PASSWORD}" != "" ]]; then
          AUTH_DIR="$(mktemp -d)"
          htpasswd -Bbn "${USERNAME}" "${PASSWORD}" > "${AUTH_DIR}/htpasswd"
          EXTRA_ARGS=(
            -v "${AUTH_DIR}:/auth"
            -e "REGISTRY_AUTH=htpasswd"
            -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
            -e "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd"
          )
        fi

        REGISTRY_VOLUME="${{ inputs.registry-volume}}"
        if [[ "${REGISTRY_VOLUME}" != "" ]]; then
          EXTRA_ARGS+=(
            -v "${REGISTRY_VOLUME}:/var/lib/registry"
          )
        fi

        docker run -d --restart=always "${EXTRA_ARGS[@]}" \
          -p "$REGISTRY_PORT:$REGISTRY_PORT" --name "$REGISTRY_NAME" registry:2

        # Connect the registry to the KinD network.
        docker network connect "kind" "$REGISTRY_NAME"

        # Make the $REGISTRY_NAME -> 127.0.0.1, to tell pushes on the host to publish to
        # this registry, even when pushing $REGISTRY_NAME:$REGISTRY_PORT/some/image
        sudo echo "127.0.0.1 $REGISTRY_NAME" | sudo tee -a /etc/hosts

    - name: Set start time output
      id: start-time
      run: echo "kind-start-time=$(echo $(($(date +%s%N)/1000000)))" >> $GITHUB_OUTPUT
      shell: bash
