version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    directories:
      # / covers .github/workflows
      - "/"
      - "/apko-build"
      - "/apt-faster"
      - "/boilerplate"
      - "/donotsubmit"
      - "/eof-newline"
      - "/githubapp-token"
      - "/gofmt"
      - "/goimports"
      - "/hugo2confluence"
      - "/inky-build-pkg"
      - "/k8s-diag"
      - "/kind-diag"
      - "/melange-build"
      - "/melange-build-pkg"
      - "/melange-keygen"
      - "/nodiff"
      - "/setup-*"
      - "/shellcheck"
      - "/terraform-diag"
      - "/trailing-space"
      - "/whereami"
      - "/wolfi-build-pkg"
