version: 2
updates:

  # workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # boilerplate
  - package-ecosystem: "github-actions"
    directory: "/boilerplate"
    schedule:
      interval: "daily"
  # digesta-bot
  - package-ecosystem: "github-actions"
    directory: "/digesta-bot"
    schedule:
      interval: "daily"
  # donotsubmit
  - package-ecosystem: "github-actions"
    directory: "/donotsubmit"
    schedule:
      interval: "daily"
  # kind-diag
  - package-ecosystem: "github-actions"
    directory: "/kind-diag"
    schedule:
      interval: "daily"