version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    directories:
      # / covers .github/workflows
      - "/"
      - "/apko-build"
      - "/apt-faster"
      - "/boilerplate"
      - "/bump-go-version-file"
      - "/chainguard-install"
      - "/clank"
      - "/donotsubmit"
      - "/eof-newline"
      - "/git-tag"
      - "/githubapp-token"
      - "/gofmt"
      - "/goimports"
      - "/hugo2confluence"
      - "/inky-build-pkg"
      - "/k8s-diag"
      - "/kind-diag"
      - "/matrix-extra-inputs"
      - "/melange-build"
      - "/melange-build-pkg"
      - "/melange-keygen"
      - "/nodiff"
      - "/otel-export"
      - "/release-notes"
      - "/setup-*"
      - "/shellcheck"
      - "/terraform-diag"
      - "/trailing-space"
      - "/wgetsum"
      - "/whereami"
      - "/wolfi-build-pkg"

  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    directories:
      - "/otel-export"

  - package-ecosystem: "gomod"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    directories:
      - "/hugo2confluence"
