# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Build image with apko'
description: |
  This action build an OCI image with apko, given a config file
  and tag to use.

inputs:
  apko_image_tag:
    description: |
      The APKO Image tag to be used in the build.
    default: v0.2.2
    required: false

  config:
    description: |
      The config file to use for building the image.
    default: .apko.yaml

  tag:
    description: |
      The tag to use for publishing the image.
    required: true

  repository_owner:
    description: |
      The repository owner's GitHub username.
    default: ${{ github.repository_owner }}

  token:
    description: |
      The repository owner's GitHub token.
    default: ${{ github.token }}

  image_refs:
    description: |
      The value to pass to --image-refs.
    default: /tmp/apko.images

outputs:
  digest:
    description: |
      The digest of the published container image.


runs:
  using: docker
  image: "docker://ghcr.io/chainguard-dev/apko:${{ inputs.apko_image_tag }}"
  env:
    # Set up go-containerregistry's GitHub keychain.
    GITHUB_ACTOR: ${{ inputs.repository_owner }}
    GITHUB_TOKEN: ${{ inputs.token }}
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      set -o errexit

      /ko-app/apko publish --image-refs="${{ inputs.image_refs }}" ${{ inputs.config }} ${{ inputs.tag }}
      echo EXIT CODE: $?
      echo ::set-output name=digest::$(cat "${{ inputs.image_refs }}")
