# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Augment a GitHub Actions build matrix to contain extra inputs.'
description: |
  This action is designed to be used to augment
  a GitHub Actions build matrix to contain extra inputs.

inputs:
  matrix-json:
    required: true
    description: |
      The original GitHub Actions matrix inputs JSON.
    default: '{}'

outputs:
  matrix-json:
    description: |
      The updated GitHub Actions matrix inputs JSON.
    value: ${{ steps.matrix-extra-inputs.outputs.matrix-json }}

runs:
  using: "composite"
  steps:
    - name: Add additional matrix inputs
      id: matrix-extra-inputs
      shell: bash
      run: |
        # Convert env vars beginning with "EXTRA_INPUT_"
        trap "rm -f inputs.json" EXIT
        echo '${{ inputs.matrix-json }}' > inputs.json
        echo "Original matrix:"
        echo "----------------"
        cat inputs.json | jq
        for kv in `env | grep '^EXTRA_INPUT_' | sed 's/^EXTRA_INPUT_//'`; do
          k="$(echo "${kv}" | cut -d "=" -f1 | tr '[:upper:]' '[:lower:]' | sed -r 's/(.)_+(.)/\1\U\2/g;s/^[a-z]/\U&/' | sed 's/.*/\l&/')"
          v="$(echo "${kv}" | cut -d "=" -f2)"
          cat inputs.json | jq -c '. + {'${k}': "'${v}'"}' > inputs.json.tmp
          mv inputs.json.tmp inputs.json
        done
        updated_matrix="$(cat inputs.json | tr -d '\n')"
        echo "matrix-json=${updated_matrix}" >> $GITHUB_OUTPUT
        echo "Updated matrix:"
        echo "----------------"
        echo "${updated_matrix}" | jq
