# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup SPDX Tools'
description: |
  This actions sets up the SPDX tools jar in the environment 
  and optionally verifies an SBOM specified in the input
  
inputs:
  sbom-path:
    description: |
      Path to the SBOM to be validated. The SBOM file name must have its extension
      matching its encoding type
    default: 

env:
  SPDX_TOOLS_VERSION: 1.1.0

on:
  pull_request:
    branches: ['main']
  push:

jobs:
  runs-on: ubuntu-latest
  sbom:
    name: SPDX Verification Tools
    steps:
      - name: Install SPDX Tools
        run: |
          wget https://github.com/spdx/tools-java/releases/download/v${SPDX_TOOLS_VERSION}/tools-java-${SPDX_TOOLS_VERSION}.zip
          unzip tools-java-${SPDX_TOOLS_VERSION}.zip
      - name: Validate SBOM
        if: ${{ inputs.sbom-path != '' }}
        run: |
          java -jar ./tools-java-${SPDX_TOOLS_VERSION}-jar-with-dependencies.jar Verify ${{ inputs.sbom-path }}
