name: "Setup terraform-docs"
description: "Install and configure terraform-docs"
branding:
  icon: edit-3
  color: green
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        shopt -s expand_aliases
        if [ -z "$NO_COLOR" ]; then
          alias log_info="echo -e \"\033[1;32mINFO\033[0m:\""
          alias log_error="echo -e \"\033[1;31mERROR\033[0m:\""
        else
          alias log_info="echo \"INFO:\""
          alias log_error="echo \"ERROR:\""
        fi
        set -e

        mkdir -p "$HOME/.terraform-docs"

        shaprog() {
          case "${RUNNER_OS}" in
            Linux)
              sha256sum "$1" | cut -d' ' -f1
              ;;
            macOS)
              shasum -a256 "$1" | cut -d' ' -f1
              ;;
            Windows)
              sha256sum "$1" | cut -d' ' -f1
              ;;
            *)
              log_error "unsupported OS ${RUNNER_OS}"
              exit 1
              ;;
          esac
        }

        terraform_docs_version='v0.24.0'
        terraform_docs_linux_amd64_sha='9005daf969de0b50134493a2c00078b49f5f5b39d021cda7c89bf4d4f3d776d3'
        terraform_docs_linux_arm64_sha='d12bd7b73c1fc9c64efc79f8157dd713dabd559f1ecf3cfc0f42e32279a155fd'
        terraform_docs_darwin_amd64_sha='3c3f7f18f908457fd1209cbe341418f7f6bae78c08126cfbe8de0d1b06aa8781'
        terraform_docs_darwin_arm64_sha='f6b114f4b032f3f9202ab6c23bfd28c3c8e68aeeb8a8f12fc118bf2073081d71'
        terraform_docs_windows_amd64_sha='afc02cbdf63726d3e5fb26a077ca1f24acd4820d7e44c21b03a3e030f9266490'
        terraform_docs_windows_arm64_sha='1168c12929531ac9132c97fff794ef531ebb2a5b54c41870b9e19911950b6fd4'
        terraform_docs_executable_name=terraform-docs

        trap "popd >/dev/null" EXIT

        pushd "$HOME/.terraform-docs" > /dev/null

        case "${RUNNER_OS}-${RUNNER_ARCH}" in
          Linux-X64)
            terraform_docs_filename=terraform-docs-${terraform_docs_version}-linux-amd64.tar.gz
            terraform_docs_sha=${terraform_docs_linux_amd64_sha}
            ;;

          Linux-ARM64)
            terraform_docs_filename=terraform-docs-${terraform_docs_version}-linux-arm64.tar.gz
            terraform_docs_sha=${terraform_docs_linux_arm64_sha}
            ;;

          macOS-X64)
            terraform_docs_filename=terraform-docs-${terraform_docs_version}-darwin-amd64.tar.gz
            terraform_docs_sha=${terraform_docs_darwin_amd64_sha}
            ;;

          macOS-ARM64)
            terraform_docs_filename=terraform-docs-${terraform_docs_version}-darwin-arm64.tar.gz
            terraform_docs_sha=${terraform_docs_darwin_arm64_sha}
            ;;

          Windows-X64)
            terraform_docs_filename=terraform-docs-${terraform_docs_version}-windows-amd64.zip
            terraform_docs_sha=${terraform_docs_windows_amd64_sha}
            terraform_docs_executable_name=terraform-docs.exe
            ;;

          Windows-ARM64)
            terraform_docs_filename=terraform-docs-${terraform_docs_version}-windows-arm64.zip
            terraform_docs_sha=${terraform_docs_windows_arm64_sha}
            terraform_docs_executable_name=terraform-docs.exe
            ;;

          *)
            log_error "unsupported architecture ${RUNNER_ARCH}"
            exit 1
            ;;
        esac

        expected_tf_docs_version_digest=${terraform_docs_sha}
        log_info "Downloading terraform-docs version '${terraform_docs_version}' from https://github.com/terraform-docs/terraform-docs/releases/download/${terraform_docs_version}/${terraform_docs_filename}"
        curl -sL https://github.com/terraform-docs/terraform-docs/releases/download/${terraform_docs_version}/${terraform_docs_filename} -o ${terraform_docs_filename}
        shaDownloaded=$(shaprog "${terraform_docs_filename}");
        if [[ ${shaDownloaded} != "${expected_tf_docs_version_digest}" ]]; then
          log_error "Unable to validate terraform-docs version: '${terraform_docs_version}': want ${expected_tf_docs_version_digest}, got ${shaDownloaded}"
          exit 1
        fi
        case "${terraform_docs_filename}" in
          *.zip)
            unzip -o "${terraform_docs_filename}"
            ;;
          *)
            tar -xzf ${terraform_docs_filename} --strip-components=0
            ;;
        esac
        chmod +x ${terraform_docs_executable_name}

    - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: printf '%s\n' "$HOME/.terraform-docs" >> "$GITHUB_PATH" # zizmor: ignore[github-env]
      shell: bash

    - if: ${{ runner.os == 'Windows' }}
      run: echo "$HOME/.terraform-docs" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append # zizmor: ignore[github-env]
      shell: pwsh
