name: New Commit
description: This action makes a new local commit using Gitsign.
on: [push]
jobs:
  commit:
    permissions:
      id-token: write # Enable OIDC
    runs-on: ubuntu-latest
    name: Create commit
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: chainguard-dev/actions/setup-gitsign@0cda751b114eb55c388e88f7479292668165602a # v1.0.2
      - shell: bash
        run: |
          # Required git config unrelated to gitsign
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          # Make the commit
          git commit --allow-empty --message="Signed commit"

          # Dump out sig data as an example to see what we just committed.
          git cat-file commit HEAD | sed -n '/BEGIN/, /END/p' | sed 's/^ //g' | sed 's/gpgsig //g' | sed 's/SIGNED MESSAGE/PKCS7/g' | openssl pkcs7 -print -print_certs -text
