# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup registry'
description: |
  This action sets up a simple in-memory OCI registry for basic testing.

inputs:
  port:
    description: The port to run the server on.
    required: true
    default: 1338

runs:
  using: "composite"

  steps:
    - name: Install crane
      uses: imjasonh/setup-crane@v0.3
    - name: Run registry
      shell: bash
      run: |
        PORT=${{inputs.port}} crane registry serve &
