# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup registry'
description: |
  This action sets up a simple in-memory OCI registry for basic testing.

inputs:
  port:
    description: The port to run the server on.
    required: true
    default: 1338
  disk:
    description: Whether to use disk for blob storage.
    required: true
    default: false

runs:
  using: "composite"

  steps:
    - name: Install crane
      if: ${{inputs.disk != 'true' }}
      uses: imjasonh/setup-crane@v0.3

    - name: Install crane
      if: ${{inputs.disk == 'true' }}
      uses: imjasonh/setup-crane@v0.3
      with:
        version: tip

    - name: Run registry
      if: ${{inputs.disk != 'true' }}
      shell: bash
      run: |
        PORT=${{inputs.port}} crane registry serve &

    - name: Run registry
      if: ${{inputs.disk == 'true' }}
      shell: bash
      run: |
        PORT=${{inputs.port}} crane registry serve --blobs-to-disk=true &
