# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup Chainguard terraform provider'
description: |
  This action sets up the Chainguard terraform provider for a particular environment.

inputs:
  environment:
    description: |
      Determines the environment from which to download the chainctl
      binary from.
    required: true
    default: enforce.dev

  identity:
    description: |
      The id of the identity that this workflow should assume for
      performing actions with chainctl.
    required: false

  audience:
    description: |
      Specifies the identity token audience to use when creating an
      identity token to authenticate with Chainguard.
      Defaults to issuer.${environment}

      This field is DEPRECATED, use identity instead.
    required: false

  invite-code:
    description: |
      Optionally specifies an invite code that allows this workflow
      register itself when run for the first time.

      Use of invite codes is DEPRECATED, use identity instead.
    required: false

runs:
  using: "composite"

  steps:
    - id: deprecation-message
      shell: bash
      run: |
        echo "*****************************************************************"
        echo "**            This action is deprecated                        **"
        echo "** please use https://github.com/chainguard-dev/setup-chainctl **"
        echo "*****************************************************************"
        echo "::warning file=action.yml,line=1,col=0,endColumn=1::Action is deprecated, check the readme"
        
    - id: default-audience
      shell: bash
      run: |
        AUDIENCE="${{ inputs.audience }}"
        if [[ -z "${AUDIENCE}" ]]; then
          AUDIENCE=issuer.${{ inputs.environment }}
        fi
        echo "audience=${AUDIENCE}" >> $GITHUB_OUTPUT

    - uses: chainguard-dev/setup-chainctl@main
      with:
        environment: ${{ inputs.environment }}
        audience: ${{ steps.default-audience.outputs.audience }}
        invite-code: ${{ inputs.invite-code }}
        identity: ${{ inputs.identity }}
