# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup Chainguard terraform provider'
description: |
  This action sets up the Chainguard terraform provider for a particular environment.

inputs:
  environment:
    description: |
      Determines the environment from which to download the chainctl
      binary from.
    required: true
    default: enforce.dev

  audience:
    description: |
      Specifies the identity token audience to use when creating an
      identity token to authenticate with Chainguard.
      Defaults to https://issuer.${environment}
    required: false

  invite-code:
    description: |
      Optionally specifies an invite code that allows this workflow
      register itself when run for the first time.
    required: false

runs:
  using: "composite"

  steps:
    - id: default-audience
      run: |
        AUDIENCE="${{ inputs.audience }}"
        if [[ -z "${AUDIENCE}" ]]; then
          AUDIENCE=https://issuer.${{ inputs.environment }}
        fi
        echo "audience=${AUDIENCE}" >> $GITHUB_OUTPUT

    - uses: chainguard-dev/actions/setup-chainctl@main
      with:
        environment: ${{ inputs.environment }}
        audience: ${{ steps.default-audience.outputs.audience }}
        invite-code: ${{ inputs.invite-code }}

    - shell: bash
      run: |
        cat > ~/.terraformrc <<EOF
        provider_installation {
          network_mirror {
            url = "https://dl.${{ inputs.environment }}/terraform-provider/"
            include = [
              "registry.terraform.io/chainguard/chainguard",
            ]
          }

          direct {
            exclude = [
              "registry.terraform.io/chainguard/chainguard",
            ]
          }
        }
        EOF
