# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup eksctl'
description: |
  Install eksctl into /usr/local/bin

inputs:
  version:
    description: 'Version of eksctl to install'
    required: true
    default: 'latest'

runs:
  using: 'composite'

  steps:
    - name: "Install eksctl"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        TEMP_D=""
        fail() { echo "FATAL:" "$@"; exit 1; }
        cleanup() {
          [ -d "$TEMP_D" ] || return 0
          rm -Rf "$TEMP_D"
        }

        TEMP_D=$(mktemp -d) || fail "could not create a temp dir"
        trap cleanup EXIT

        cd "$TEMP_D" || fail "could not cd to $TEMP_D"

        [ -n "$VERSION" ] || fail "version input is empty"

        # install eksctl
        m=$(uname -m)
        case "$m" in
          x86_64) arch=amd64;;
          aarch64) arch=arm64;;
          *) fail "unknown output for 'uname -m': '$m'";;
        esac
        uname_s=$(uname -s) || fail "uname -s failed"
        platform="${uname_s}_${arch}"
        fname="eksctl_${platform}.tar.gz"

        burl="https://github.com/eksctl-io/eksctl/releases"
        if [ "$VERSION" = "latest" ]; then
          url="$burl/$VERSION/download"
        else
          url="$burl/download/$VERSION"
        fi

        echo "download eksctl for $platform platform from $url/$fname"
        curl -sL "$url/$fname" > "$fname" ||
          fail "download failed $url"

        cksum_url="$url/eksctl_checksums.txt"
        echo "verify download against ${cksum_url}"
        curl -sL "${cksum_url}" > checksums.txt ||
          fail "failed to download checksums from $cksum_url"
        grep "$fname" checksums.txt > checksums.platform || {
          cat checksums.txt
          fail "$fname was not found in checksums.txt (content above)"
        }
        sha256sum --check < checksums.platform ||
          fail "checksum verification of $fname failed"

        echo "extract to /usr/local/bin"
        mkdir -p /usr/local/bin
        tar -C /usr/local/bin -xvf "$fname"

    - name: "Show eksctl info"
      shell: bash
      run: |
        /usr/local/bin/eksctl info
