# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup chainctl'
description: |
  This action sets up the Chainguard chainctl CLI and authenticates
  it against the target environment.

inputs:
  environment:
    description: |
      Determines the environment from which to download the chainctl
      binary from.
    required: true
    default: enforce.dev

  identity:
    description: |
      The id of the identity that this workflow should assume for
      performing actions with chainctl.
    required: false

  audience:
    description: |
      Specifies the identity token audience to use when creating an
      identity token to authenticate with Chainguard.
      Defaults to issuer.${environment}

      This field is DEPRECATED, use identity instead.
    required: false

  invite-code:
    description: |
      Optionally specifies an invite code that allows this workflow
      register itself when run for the first time.

      Use of invite codes is DEPRECATED, use identity instead.
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "*****************************************************************"
        echo "**    This is deprecated and will be removed around Aug/2024   **"
        echo "** please use https://github.com/chainguard-dev/setup-chainctl **"
        echo "*****************************************************************"
        echo "::warning file=action.yml,line=1,col=0,endColumn=1::Action is deprecated, check the readme"

    - uses: chainguard-dev/setup-chainctl@58c1184bfdcf53576831252e68198d8df26f3e1b # v0.1.0
      id: digesta
      with:
        environment: ${{ inputs.environment }}
        identity: ${{ inputs.identity }}
        audience: ${{ inputs.audience }}
        invite-code: ${{ inputs.invite-code }}
