# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup melange'
description: |
  Sets up melange, so it can run in an Ubuntu environment.

runs:
  using: 'composite'

  steps:
    - name: 'Fetch apk-tools'
      shell: bash
      run: |
        wget 'https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/apk-tools-static-2.12.9-r3.apk'
        tar zxf apk-tools-static-2.12.9-r3.apk sbin/apk.static
        sudo mv sbin/apk.static /sbin/apk
        rm apk-tools-static-2.12.9-r3.apk
    - name: 'Set up apk-tools in overlay mode'
      shell: bash
      run: |
        sudo apk add --initdb --root=/
        (cat <<_EOF_
        https://dl-cdn.alpinelinux.org/alpine/edge/main
        _EOF_
        ) | sudo tee /etc/apk/repositories
    - name: 'Fetch and install alpine keyring'
      shell: bash
      run: |
        sudo apk update --allow-untrusted
        sudo apk add --allow-untrusted alpine-keys
    - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.1.5
      with:
        go-version: 1.18.x
    - name: 'Install dependencies'
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y build-essential git bubblewrap proot
    - name: 'Install melange'
      shell: bash
      run: |
        git clone https://github.com/chainguard-dev/melange
        pushd melange
        make melange
        sudo env "PATH=$PATH" make install
        melange version
        popd
        rm -rf ./melange
