# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Setup melange'
description: |
  Sets up melange, so it can run in an Ubuntu environment.

runs:
  using: 'composite'

  steps:
    # FIXME(kaniini): Switch to qemu-user-static when apko 0.5/melange 0.2 is released.
    - name: 'Update package repository indexes'
      shell: bash
      run: |
        sudo apt update
    - name: 'Install qemu emulator binaries'
      shell: bash
      run: |
        sudo apt install -y qemu-user
    - name: 'Fetch apk-tools nightly'
      shell: bash
      run: |
        sudo apt install -y unzip
        wget -O apk-tools-nightly.zip 'https://gitlab.alpinelinux.org/alpine/apk-tools/-/jobs/artifacts/2.12-stable/download?job=build-static:+[x86_64]'
        unzip apk-tools-nightly.zip 'src/apk.static-x86_64'
        sudo mv 'src/apk.static-x86_64' /sbin/apk
        rm -rf src apk-tools-nightly.zip
    - name: 'Set up apk-tools in overlay mode'
      shell: bash
      run: |
        sudo apk add --initdb --root=/
        (cat <<_EOF_
        https://dl-cdn.alpinelinux.org/alpine/edge/main
        _EOF_
        ) | sudo tee /etc/apk/repositories
    - name: 'Fetch and install alpine keyring'
      shell: bash
      run: |
        sudo apk update --allow-untrusted
        sudo apk add --allow-untrusted alpine-keys
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3.2
      with:
        go-version: 1.18
        check-latest: true
    - name: 'Install dependencies'
      shell: bash
      run: |
        sudo apt install -y build-essential git proot
    # TODO: the bubblewrap package available from "apt install"
    # is outdated and missing newer features such as --clearenv flag,
    # so instead we download the wolfi .apk and use the binary in there
    - name: 'Install dependencies (bubblewrap)'
      env:
        BWRAP_APK_VERSION: 0.6.2-r0
        BWRAP_APK_SHA256: 9fd6136990afd7e5d1223df536518f380d454724d8a2ed2ffa20f671843cee69
      shell: bash
      run: |
        set -x
        curl -vL -o bwrap.tar.gz "https://packages.wolfi.dev/os/x86_64/bubblewrap-${BWRAP_APK_VERSION}.apk"
        echo "${BWRAP_APK_SHA256}  bwrap.tar.gz" | sha256sum -c
        tar -zxvf bwrap.tar.gz --strip-components=2 usr/bin/bwrap
        sudo mv bwrap /sbin/bwrap
        rm -f bwrap.tar.gz
    - name: 'Install melange'
      shell: bash
      run: |
        git clone https://github.com/chainguard-dev/melange
        pushd melange
        make melange
        sudo env "PATH=$PATH" make install
        melange version
        popd
        rm -rf ./melange
