# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'gofmt'
description: |
  This action runs gofmt over the working tree and then verifies
  that there are no differences from running the tool.

inputs:
  args:
    description: |
      The arguments to pass to gofmt
    required: false

runs:
  using: "composite"
  steps:
  - name: gofmt ${{ inputs.args }}
    shell: bash
    run: |
      # We limit the depth to 3 mostly to avoid go.mod files that get pulled into `third_party` like some hashicorp repos.
      for dir in $(find . -type d \( -path "*/third_party" -o -path "*/.terraform" \) -prune -o -name go.mod -exec dirname {} \;| sort ); do
        echo "::group:: $dir"
        pushd $dir
        gofmt ${{ inputs.args }} -w \
          $(find . \
          -path './vendor' -prune \
          -o -path '*/third_party' -prune \
          -o -name '*.pb.go' -prune \
          -o -name '*.pb.gw.go' -prune \
          -o -name 'wire_gen.go' -prune \
          -o -type f -name '*.go' -print)
        popd
        echo ::endgroup::
      done

  - name: Verify gofmt
    uses: chainguard-dev/actions/nodiff@main
    with:
      fixup-command: "gofmt ${{ inputs.args }}"
