# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Build package with melange'
description: |
  This action builds a single package using Melange, given a config file.
  It deals with setting up the Melange build tool, repository, and signing
  key.

inputs:
  config:
    description: |
      The config file to use for building the package.
    default: .melange.yaml

  archs:
    description: |
      The architectures to use.
    default: x86_64

  sign-with-temporary-key:
    description: |
      Sign packages with a temporary key, useful for multi-stage
      pipelines.
    default: false

  signing-key-path:
    description: |
      The path for the temporary key if signing is enabled.
    default: ${{ github.workspace }}/melange.rsa

runs:
  using: 'composite'

  steps:
    - uses: chainguard-dev/actions/setup-melange@main
    # TODO(kaniini): enable keyless signing once it lands
    - uses: chainguard-dev/actions/melange-keygen@main
      if: ${{ inputs.sign-with-temporary-key }}
      with:
        signing-key-path: ${{ inputs.signing-key-path }}
    - uses: chainguard-dev/actions/melange-build-pkg@main
      with:
        config: ${{ inputs.config }}
        archs: ${{ inputs.archs }}
        sign-with-key: ${{ inputs.sign-with-temporary-key }}
        signing-key-path: ${{ inputs.signing-key-path }}
    - uses: chainguard-dev/actions/melange-index@main
      with:
        archs: ${{ inputs.archs }}
        sign-with-key: ${{ inputs.sign-with-temporary-key }}
        signing-key-path: ${{ inputs.signing-key-path }}
