# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Do Not Submit'
description: |
  This action flags occurrences of the string "DO NOT SUBMIT"
  throughout the source tree.  This enables developers to flag
  pieces of code they intend to revisit before submitting with
  this string and have CI block the change from merging.

inputs: {}

runs:
  using: "composite"
  steps:
  - uses: reviewdog/action-setup@8f2ec89e6b467ca9175527d2a1641bbd0c05783b # v1.0.3
    with:
      reviewdog_version: latest

  - name: Do Not Submit
    shell: bash
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
    run: |
      set -e
      cd "${GITHUB_WORKSPACE}" || exit 1

      echo '::group:: Running DO NOT SUBMIT with reviewdog 🐶 ...'
      # Don't fail because of grep
      set +o pipefail
      find . -type f -not -path './vendor/*' -not -path './third_party/*' -not -path './.git/*' |
      xargs grep -n "DO NOT SUBMIT" |
      reviewdog -efm="%f:%l:%m" \
            -name="DO NOT SUBMIT" \
            -reporter="github-pr-check" \
            -filter-mode="added" \
            -fail-on-error="true" \
            -level="error"
      echo '::endgroup::'
