name: 'Update the image digest'
description: 'Update the image digest when have a mutating tag'

inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    required: true
    default: ${{ github.token }}
  signoff:
    description: 'Add `Signed-off-by` line by the committer at the end of the commit log message.'
    default: false
  author:
    description: >
      The author name and email address in the format `Display Name <email@address.com>`.
      Defaults to the user who triggered the workflow run.
    default: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
  committer:
    description: >
      The committer name and email address in the format `Display Name <email@address.com>`.
      Defaults to the GitHub Actions bot user.
    default: 'GitHub <noreply@github.com>'
  labels-for-pr:
    description: 'A comma or newline separated list of labels to be used in the pull request.'
    default: automated pr, kind/cleanup, release-note-none
  branch-for-pr:
    description: 'The pull request branch name.'
    default: 'update-digests'
  title-for-pr:
    description: 'The title of the pull request.'
    default: 'Update images digests'
  commit-message:
    description: 'The message to use when committing changes.'
    default: 'Update images digests'
  create-pr:
    description: 'Create a PR or just keep the changes locally.'
    default: true

outputs:
  pull_request_number:
    description: "Pull Request Number"
    value: ${{ steps.digesta.outputs.pull-request-number }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "***********************************************************************************************"
        echo "**              This is deprecated and will be removed around Aug/2024                       **"
        echo "**    Digestabot have a new home please use https://github.com/chainguard-dev/digestabot     **"
        echo "** This action is redirecting to the new one in https://github.com/chainguard-dev/digestabot **"
        echo "***********************************************************************************************"
        echo "::warning file=action.yml,line=1,col=0,endColumn=1::Action is deprecated, check the readme"

    - uses: chainguard-dev/digestabot@4298e530896fb4164f9c89030c561b75b9321149 # v1.0.2
      id: digesta
      with:
        token: ${{ inputs.token }}
        signoff: ${{ inputs.signoff }}
        author: ${{ inputs.author }}
        committer: ${{ inputs.committer }}
        labels-for-pr: ${{ inputs.labels-for-pr }}
        branch-for-pr: ${{ inputs.branch-for-pr }}
        title-for-pr: ${{ inputs.title-for-pr }}
        commit-message: ${{ inputs.commit-message }}
        create-pr: ${{ inputs.create-pr }}
