# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Build Inky package with melange'
description: |
  This action builds a single package using Melange, given a config file.
  It deals with setting up the Melange build tool, repository, and signing
  key.  It composes the melange-build-pkg option with defaults appropriate
  for Inky.

inputs:
  package-name:
    description: |
      The package name to build.

  archs:
    description: |
      The architectures to use.
    default: x86_64

  signing-key-name:
    description: |
      The name of the signing key to use if signing is enabled.
    default: wolfi-signing.rsa

  repository-path:
    description: |
      The path of the repository being constructed by Melange.
    default: ${{ github.workspace }}/packages

runs:
  using: 'composite'

  steps:
    - shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/${{ inputs.package-name }}
    - uses: chainguard-dev/actions/melange-build-pkg@081e79ee578199ef583d4ca74edc376b50b9409c # v1.6.0
      with:
        config: ${{ inputs.package-name }}.yaml
        archs: ${{ inputs.archs }}
        sign-with-key: true
        update-index: true
        repository-append: ${{ github.workspace }}/packages
        keyring-append: /etc/apk/keys/${{ inputs.signing-key-name }}.pub
        workspace-dir: ${{ github.workspace }}/build/${{ inputs.package-name }}
        signing-key-path: ${{ github.workspace }}/${{ inputs.signing-key-name }}
        source-dir: ${{ github.workspace }}/${{ inputs.package-name }}
        empty-workspace: false
