name: "Setup gitsign"
description: "Install and configure gitsign"
branding:
  icon: edit-3
  color: green
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        shopt -s expand_aliases
        if [ -z "$NO_COLOR" ]; then
          alias log_info="echo -e \"\033[1;32mINFO\033[0m:\""
          alias log_error="echo -e \"\033[1;31mERROR\033[0m:\""
        else
          alias log_info="echo \"INFO:\""
          alias log_error="echo \"ERROR:\""
        fi
        set -e

        mkdir -p "$HOME/.gitsign"

        shaprog() {
          case "${RUNNER_OS}" in
            Linux)
              sha256sum "$1" | cut -d' ' -f1
              ;;
            macOS)
              shasum -a256 "$1" | cut -d' ' -f1
              ;;
            Windows)
              powershell -command "(Get-FileHash $1 -Algorithm SHA256 | Select-Object -ExpandProperty Hash).ToLower()"
              ;;
            *)
              log_error "unsupported OS ${RUNNER_OS}"
              exit 1
              ;;
          esac
        }

        gitsign_version='0.16.1'
        gitsign_linux_amd64_sha='4a29a1f4b9add1f0f6d9a3e9e6ba0cffa121b971be82d62bb1496d7d1d877b0a'
        gitsign_linux_arm64_sha='66eb0378608c8fbceb497eecb58a525345549f46e9588616daa0f157624f33b4'
        gitsign_darwin_amd64_sha='4cbfe135bea8bc7b82b528dbf940ef02cdf2d11b2e108fafd621b5b60abe3743'
        gitsign_darwin_arm64_sha='acf5650c021a47a6e9a33463aa31eb6a93e5616d03cfbe6641f7ff669034095c'
        gitsign_windows_amd64_sha='553e798dec1f9f9835a73d2b89343678710e9754525df36c169ff16906d549f9'
        gitsign_windows_arm64_sha='ef8ac74018c10cd6644bd64c9a6cf857dc28a99a8184f1301067bf82d1c4f926'
        gitsign_executable_name=gitsign

        trap "popd >/dev/null" EXIT

        pushd "$HOME/.gitsign" > /dev/null

        case "${RUNNER_OS}-${RUNNER_ARCH}" in
          Linux-X64)
            gitsign_filename=gitsign_${gitsign_version}_linux_amd64
            gitsign_sha=${gitsign_linux_amd64_sha}
            ;;

          Linux-ARM64)
            gitsign_filename=gitsign_${gitsign_version}_linux_arm64
            gitsign_sha=${gitsign_linux_arm64_sha}
            ;;

          macOS-X64)
            gitsign_filename=gitsign_${gitsign_version}_darwin_amd64
            gitsign_sha=${gitsign_darwin_amd64_sha}
            ;;

          macOS-ARM64)
            gitsign_filename=gitsign_${gitsign_version}_darwin_arm64
            gitsign_sha=${gitsign_darwin_arm64_sha}
            ;;

          Windows-X64)
            gitsign_filename=gitsign_${gitsign_version}_windows_amd64.exe
            gitsign_sha=${gitsign_windows_amd64_sha}
            gitsign_executable_name=gitsign.exe
            ;;

          Windows-ARM64)
            gitsign_filename=gitsign_${gitsign_version}_windows_arm64.exe
            gitsign_sha=${gitsign_windows_arm64_sha}
            gitsign_executable_name=gitsign.exe
            ;;

          *)
            log_error "unsupported architecture ${RUNNER_ARCH}"
            exit 1
            ;;
        esac

        expected_gitsign_version_digest=${gitsign_sha}
        log_info "Downloading gitsign version 'v${gitsign_version}' from https://github.com/sigstore/gitsign/releases/download/v${gitsign_version}/${gitsign_filename}"
        curl -sL https://github.com/sigstore/gitsign/releases/download/v${gitsign_version}/${gitsign_filename} -o ${gitsign_executable_name}
        shaDownloaded=$(shaprog "${gitsign_executable_name}");
        if [[ ${shaDownloaded} != "${expected_gitsign_version_digest}" ]]; then
          log_error "Unable to validate gitsign version: 'v${gitsign_version}': want ${expected_gitsign_version_digest}, got ${shaDownloaded}"
          exit 1
        fi
        chmod +x ${gitsign_executable_name}

        # Configure
        git config --global commit.gpgsign true       # Sign all commits
        git config --global tag.gpgsign true          # Sign all tags
        git config --global gpg.x509.program gitsign  # Use gitsign for signing
        git config --global gpg.format x509           # gitsign expects x509 args

        # Use workflow name as the username
        git config --global user.name "${GITHUB_WORKFLOW}"
        # This email identifies the commit as GitHub Actions - see https://github.com/orgs/community/discussions/26560
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: printf '%s\n' "$HOME/.gitsign" >> "$GITHUB_PATH"
      shell: bash

    - if: ${{ runner.os == 'Windows' }}
      run: echo "$HOME/.gitsign" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
