name: "Setup gitsign"
description: "Install and configure gitsign"
branding:
  icon: edit-3
  color: green
# TODO: Allow configurable versions / arch
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -ex

        # Install
        curl -fsL https://github.com/sigstore/gitsign/releases/download/v0.0.2-alpha/gitsign_0.0.2-alpha_linux_amd64 -o /usr/local/bin/gitsign
        chmod +x /usr/local/bin/gitsign

        # Configure
        git config --global commit.gpgsign true       # Sign all commits
        git config --global gpg.x509.program gitsign  # Use gitsign for signing
        git config --global gpg.format x509           # gitsign expects x509 args
