# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Index packages with Melange'
description: |
  This action generates a Melange repository index.

inputs:
  archs:
    description: |
      The architectures to use.
    default: x86_64

  sign-with-key:
    description: |
      Sign packages with a key, useful for multi-stage
      pipelines.
    default: false

  signing-key-path:
    description: |
      The path for the temporary key if signing is enabled.
    default: ${{ github.workspace }}/melange.rsa

  repository-path:
    description: |
      The path of the repository being constructed by Melange.
    default: ${{ github.workspace }}/packages

runs:
  using: 'composite'

  steps:
    - name: 'Index packages with Melange'
      shell: bash
      run: |

        parsed_archs=""
        for p_arch in $(echo ${{ inputs.archs }} | tr "," " "); do

          case $p_arch in
            "386")
              parsed_archs+="x86 "
              ;;
            "amd64")
              parsed_archs+="x86_64 "
              ;;
            "arm64")
              parsed_archs+="aarch64 "
              ;;
            "arm/v6")
              parsed_archs+="armhf "
              ;;
            "arm/v7")
              parsed_archs+="armv7 "
              ;;
            *)
              parsed_archs+="$p_arch "
              ;;
          esac
        done

        for arch in $parsed_archs; do
          pushd ${{ inputs.repository-path }}/$arch
          apk index -o APKINDEX.tar.gz *.apk
          ${{ inputs.sign-with-key }} && melange sign-index --signing-key=${{ inputs.signing-key-path }} APKINDEX.tar.gz
          popd
        done
