name: test-terraform-docs

on:
  pull_request:
    paths:
      - 'setup-terraform-docs/**'
      - '.github/workflows/test-terraform-docs.yaml'

permissions: {}

jobs:
  test_terraform_docs_action:

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - macos-14
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    name: Install Terraform Docs and test presence in path
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: block
        allowed-endpoints: >
          *.blob.core.windows.net:443
          *.githubapp.com:443
          github.com:443
          release-assets.githubusercontent.com:443

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Install Terraform Docs
      uses: ./setup-terraform-docs

    - name: Check install!
      run: terraform-docs version
