name: test-git-tag

on:
  pull_request:
    paths:
      - "git-tag/**"
      - ".github/workflows/test-git-tag.yaml"

permissions: {}

jobs:
  test_git_tag_action:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    name: Test Git Tag
    steps:
      - uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            github.com:443
            raw.githubusercontent.com:443
            release-assets.githubusercontent.com:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./git-tag
        with:
          git_tag_prefix: "v"
          bump_level: major
          dry_run: true
          forced_version: 2.0.0
