name: test-argo-workflows

on:
  pull_request:
    paths:
      - 'setup-argo-workflows/**'
      - '.github/workflows/test-argo-workflows.yaml'

permissions: {}

jobs:
  test_argo_workflows_action:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: read

    name: Install Argo Workflows and test presence in path
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit # TODO(harden-runner): switch to block once IPv6 multicast (ff02::1) is supported (kind uses Docker container networking)
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            auth.docker.io:443
            cdn01.quay.io:443
            github.com:443
            production.cloudflare.docker.com:443
            quay.io:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Kind
        uses: chainguard-dev/actions/setup-kind@de68b87302e6266db5fb5220246f8aa46fe94b67 # v1.6.14

      - name: Install Argo Workflows
        uses: ./setup-argo-workflows

      - name: Check install!
        run: argo lint --help

  test_argo_cli_only:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: read

    name: Install Argo CLI only and test presence in path
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            auth.docker.io:443
            cdn01.quay.io:443
            github.com:443
            production.cloudflare.docker.com:443
            quay.io:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Argo Workflows
        uses: ./setup-argo-workflows
        with:
          install-argo-cli-only: 'true'

      - name: Check install!
        run: argo lint --help
