name: test-matrix-extra-inputs

on:
  pull_request:

permissions: {}

jobs:
  test_action:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: block
        allowed-endpoints: >
          *.blob.core.windows.net:443
          *.githubapp.com:443
          github.com:443

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - id: extra-inputs
      uses: ./matrix-extra-inputs
      with:
        matrix-json: '{"x":1,"y":2}'
      env:
        EXTRA_INPUT_THIS_IS_EXAMPLE: hello
        EXTRA_INPUT_THIS_IS_ALSO_EXAMPLE: world

    - id: check-matrix-output
      env:
        MATRIX_JSON: ${{ steps.extra-inputs.outputs.matrix-json }}
      run: |
        set -x
        printf '%s\n' "$MATRIX_JSON" > input.json
        [[ "$(jq -r .x input.json)" == "1" ]]
        [[ "$(jq -r .y input.json)" == "2" ]]
        [[ "$(jq -r .thisIsExample input.json)" == "hello" ]]
        [[ "$(jq -r .thisIsAlsoExample input.json)" == "world" ]]
