name: test-argo-workflows

on:
  pull_request:
    paths:
      - 'setup-argo-workflows/**'
      - '.github/workflows/test-argo-workflows.yaml'

permissions: {}

jobs:
  test_argo_workflows_action:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: read

    name: Install Argo Workflows and test presence in path
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Kind
        uses: chainguard-dev/actions/setup-kind@c29bd2a0f4e71ad61a209c255c0164987df76aaa # v1.6.10

      - name: Install Argo Workflows
        uses: ./setup-argo-workflows

      - name: Check install!
        run: argo lint --help

  test_argo_cli_only:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: read

    name: Install Argo CLI only and test presence in path
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Argo Workflows
        uses: ./setup-argo-workflows
        with:
          install-argo-cli-only: 'true'

      - name: Check install!
        run: argo lint --help
