name: test-setup

on:
  pull_request:
    branches: [ main ]

jobs:
  test-setup:
    name: test-setup
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout the current action
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    # Test that installers successfully install.
    - uses: ./setup-chainctl
    - uses: ./setup-chainguard-terraform
